In [31]:
import torch
import torch.nn as nn

class Net(nn.Module):
    
    # 모델의 구성 요소 생성 및 구조 설정
    def __init__(self):
        super(Net, self).__init__()
        
        self.input = nn.Linear(8, 4)
        self.fc2 = nn.Linear(4, 2)
        self.fc3 = nn.Linear(2, 1)
        
    # 순방향 학습 진행 함수
    def forward(self, x):
        return self.fc3(self.fc2(self.fc1(x)))

In [45]:
import torch
import torch.nn as nn
import torchviz
from torchinfo import summary


class Net(nn.Module):
    
    # 모델의 구성 요소 생성 및 구조 설정
    def __init__(self):
        super(Net, self).__init__()
        
        self.input = nn.Linear(8, 4)
        self.layer2 = nn.Linear(4, 2)
        self.dropout = nn.Dropout(0.5)
        self.layer3 = nn.Linear(2, 1)
        
    # 순방향 학습 진행 함수
    def forward(self, x):
        return self.layer3(self.dropout(self.layer2(self.input(x))))

In [46]:
# 모델 인스턴스 생성
model = Net()

print(model)

summary(model)

Net(
  (input): Linear(in_features=8, out_features=4, bias=True)
  (layer2): Linear(in_features=4, out_features=2, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (layer3): Linear(in_features=2, out_features=1, bias=True)
)


Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Dropout: 1-3                           --
├─Linear: 1-4                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0

In [47]:
model.modules
model.input

Linear(in_features=8, out_features=4, bias=True)

In [48]:
model.input.weight, model.layer2.bias

(Parameter containing:
 tensor([[ 0.0025, -0.2335,  0.2672, -0.2603,  0.0776,  0.3455, -0.2869, -0.3216],
         [-0.2821, -0.0591, -0.0734, -0.0423,  0.0483,  0.1500,  0.1090,  0.1834],
         [-0.1777,  0.3236,  0.1739,  0.1905,  0.1567,  0.0574, -0.1045, -0.1545],
         [-0.0388,  0.0572,  0.1784,  0.2839, -0.0143, -0.1727,  0.2968, -0.2785]],
        requires_grad=True),
 Parameter containing:
 tensor([0.1584, 0.4379], requires_grad=True))

In [49]:
# 모델 인스턴스 속성 확인
model.parameters()

<generator object Module.parameters at 0x00000267DC76D820>

In [50]:
for param in model.parameters():
    print(param, end="\n\n") # 초기화 전

Parameter containing:
tensor([[ 0.0025, -0.2335,  0.2672, -0.2603,  0.0776,  0.3455, -0.2869, -0.3216],
        [-0.2821, -0.0591, -0.0734, -0.0423,  0.0483,  0.1500,  0.1090,  0.1834],
        [-0.1777,  0.3236,  0.1739,  0.1905,  0.1567,  0.0574, -0.1045, -0.1545],
        [-0.0388,  0.0572,  0.1784,  0.2839, -0.0143, -0.1727,  0.2968, -0.2785]],
       requires_grad=True)

Parameter containing:
tensor([0.0265, 0.2323, 0.0547, 0.1674], requires_grad=True)

Parameter containing:
tensor([[ 0.3770, -0.4838,  0.3449, -0.1876],
        [-0.1572, -0.4683,  0.0078,  0.3092]], requires_grad=True)

Parameter containing:
tensor([0.1584, 0.4379], requires_grad=True)

Parameter containing:
tensor([[-0.1217,  0.3319]], requires_grad=True)

Parameter containing:
tensor([-0.0752], requires_grad=True)


In [51]:
# 모델의 각 층별 w, b 텐서 정보 확인 
for param in model.named_parameters():
    print(param, end="\n\n")

('input.weight', Parameter containing:
tensor([[ 0.0025, -0.2335,  0.2672, -0.2603,  0.0776,  0.3455, -0.2869, -0.3216],
        [-0.2821, -0.0591, -0.0734, -0.0423,  0.0483,  0.1500,  0.1090,  0.1834],
        [-0.1777,  0.3236,  0.1739,  0.1905,  0.1567,  0.0574, -0.1045, -0.1545],
        [-0.0388,  0.0572,  0.1784,  0.2839, -0.0143, -0.1727,  0.2968, -0.2785]],
       requires_grad=True))

('input.bias', Parameter containing:
tensor([0.0265, 0.2323, 0.0547, 0.1674], requires_grad=True))

('layer2.weight', Parameter containing:
tensor([[ 0.3770, -0.4838,  0.3449, -0.1876],
        [-0.1572, -0.4683,  0.0078,  0.3092]], requires_grad=True))

('layer2.bias', Parameter containing:
tensor([0.1584, 0.4379], requires_grad=True))

('layer3.weight', Parameter containing:
tensor([[-0.1217,  0.3319]], requires_grad=True))

('layer3.bias', Parameter containing:
tensor([-0.0752], requires_grad=True))


# Layer에 가중치 설정 xavier_uniform_

In [52]:
# 세비어 알고리즘의 가중치 초기화
nn.init.xavier_uniform_(model.input.weight)

Parameter containing:
tensor([[ 0.6615, -0.3484, -0.6576,  0.5226, -0.1742,  0.6987,  0.0679, -0.4854],
        [ 0.1127, -0.3136, -0.3664,  0.2048, -0.2669, -0.5822, -0.3865, -0.1401],
        [ 0.5586, -0.2985,  0.6064,  0.1034, -0.6728,  0.2198, -0.4171, -0.2996],
        [-0.0101, -0.0021, -0.3988, -0.6555, -0.6657,  0.3560,  0.6085, -0.3568]],
       requires_grad=True)

In [53]:
# 헤 알고리즘의 가중치 초기화
nn.init.kaiming_normal_(model.layer2.weight)

Parameter containing:
tensor([[-0.6916, -0.4593, -0.1840, -0.1828],
        [-0.8356,  0.0716,  0.2428,  0.2269]], requires_grad=True)

In [54]:
# 모델 구성 모든 Layer 가져오기
for child in model.children():
    print(child, end="\n\n")
    
for child in model.named_children():
    print(child, end="\n\n")

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Dropout(p=0.5, inplace=False)

Linear(in_features=2, out_features=1, bias=True)

('input', Linear(in_features=8, out_features=4, bias=True))

('layer2', Linear(in_features=4, out_features=2, bias=True))

('dropout', Dropout(p=0.5, inplace=False))

('layer3', Linear(in_features=2, out_features=1, bias=True))


In [55]:
torch.save(model, '../data/model/mymodel.pt')

In [56]:
mymodel = torch.load('../data/model/mymodel.pt')
mymodel

Net(
  (input): Linear(in_features=8, out_features=4, bias=True)
  (layer2): Linear(in_features=4, out_features=2, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (layer3): Linear(in_features=2, out_features=1, bias=True)
)

In [1]:
a = 2