# 목표 : __선형__ 모델 기반의 __분류__ 모델 구현
- 데이터 : iris
- 피쳐 : 2개
- 타겟 3개

## <hr>1. 모듈 로딩 & 데이터 준비

In [61]:
# 모듈 로딩
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [62]:
# 데이터 로딩 -> bunch라는 데이터 타입
load_iris()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [63]:
dataXy = load_iris(return_X_y=True) # feature와 target만 들어옴 
dataXy

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [64]:
dataDF = load_iris(return_X_y=True, as_frame=True) # feature와 target을 DF형식으로 줌
dataDF[0]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [65]:
dataDF[1]

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [66]:
data = load_iris(as_frame=True)
featureDF= data["data"]
featureDF

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [67]:
targetDF = data["target"]
targetDF

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

## 2. 학습진행

In [68]:
from sklearn.linear_model import LogisticRegression

In [69]:
# 모델 인스턴스 생성
model = LogisticRegression()
model.fit(featureDF, targetDF)

C:\Users\kdp\anaconda3\envs\EXAM_ML\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

warning이 뜨는데 반복횟수가 부족하다거나 이런 거임 읽어보고 파라미터 추가

In [70]:
model = LogisticRegression(max_iter=1000)
model.fit(featureDF, targetDF)

LogisticRegression(max_iter=1000)

In [71]:
# 학습 후 결정된 모델 파라미터 확인 
print("classes_ : ", model.classes_)
print("=" * 50)
print("feature_names_in_", model.feature_names_in_)
print("=" * 50)
print("n_iter_", model.n_iter_)
print("=" * 50)
print("coef_ :", model.coef_)
print("=" * 50)
print("intercept_ :", model.intercept_) # 3개면 3개 뜸 분류할 것이 2개라면 하나만 학습함 coef_? intercept_ 개수 확인 

classes_ :  [0 1 2]
feature_names_in_ ['sepal length (cm)' 'sepal width (cm)' 'petal length (cm)'
 'petal width (cm)']
n_iter_ [120]
coef_ : [[-0.42364806  0.96739434 -2.51708319 -1.07937296]
 [ 0.53447765 -0.3216458  -0.20639707 -0.94423775]
 [-0.11082959 -0.64574854  2.72348026  2.02361071]]
intercept_ : [  9.84997373   2.23721656 -12.08719029]


In [72]:
model.score(featureDF, targetDF)

0.9733333333333334

In [73]:
model.predict(featureDF.iloc[[0]]) # 첫번째 행을 넣어보자 -> 종이 나옴

array([0])

In [ ]:
model.predict(featureDF.iloc[[-1]]) # 마지막 행을 넣어보자 -> 종이 나옴 

In [77]:
# 각 분류 클래스에 대한 확률값
np.round(model.predict_proba(featureDF.iloc[[-1]]), 3)

array([[0.   , 0.235, 0.765]])

In [75]:
# 각 분류기의 선형식에서 계산한 값
model.decision_function(featureDF.iloc[[-1]]) # 위에 coef_에 feature곲하고 intercept_ 더해서 나온 결과

# ovr의 경우 이게 여러게 나오고 한줄 한줄이 logistic이 아닌 softmax로 들어가서 확률이 나오는 것

array([[-4.52736242,  1.67344429,  2.85391813]])

R - 나머지  
One v

과일 => 사과 여부를 판단하는 : 이진분류
<hr>
과일 => 과일을 분류하는 모델 : 다중분류(3개부터~) => OvR/OvA => 2진 분류기가 클래스 개수만큼 생성<br>
타겟  <br>
사과 => 사과 vs 나머지<br>
배 => 배 vs 나머지<br>
...
<hr>
과일 => 과일을 분류하는 모델 OvO 5*4=20  5*4=20/10<br>
타겟  <br>
사과   => 사과 vs 배 사과vs바나나 사과vs수박 사과vs키위  <br>
배     => 배vs사과 배vs바나나 배vs수박 배vs키위 <br>
바나나 => 바나나vs사과 바나나vs배 바나나vs수박 바나나vs키위<br>
수박   => 수박vs사과 수박vs배 수박vs바나나 수박vs키위<br>
키위   => 키위vs사과 키위vs배 키위vs바나나 키위vs수박<br>

<hr>
[OvA/OvR] ==> 3개 모델
Setosa : Setosa vs 나머지
Versicolor : Versicolor vs 나머지
Virginica : Virginica vs 나머지 

[OvO] ==> (3*2)/2 = 3개 모델

|제목|내용|
Setosa vs Versicolor-Setosa vs Versicolor-
|Versicolor vs Setosa|ersicolor vs Virginica|
|Virginica vs Setosa|Virginica vs Versicolor|r