# 기본적인 이미지 다루기

In [2]:
# 모듈로딩
import cv2
import numpy as np

## 이미지 데이터 로딩
- 컬러/회색 이미지 변환로딩 가능

In [9]:
file = "../data/img/img3.png"

In [10]:
# 컬러 이미지 로딩 color가 default 
img_rgb = cv2.imread(file, cv2.IMREAD_COLOR)

# 회색 이미지 로딩
img_gray = cv2.imread(file, cv2.IMREAD_GRAYSCALE)

In [11]:
# 이미지 데이터 정보 확인 
print(f"[Color Image]")
print(f"SHAPE: {img_rgb.shape} --- DIM : {img_rgb.ndim}차원")
print(f"DTYPE: {img_rgb.dtype} --- SIZE : {img_rgb.size}바이트")

[Color Image]
SHAPE: (511, 568, 3) --- DIM : 3차원
DTYPE: uint8 --- SIZE : 870744바이트


In [12]:
# 이미지 데이터 정보 확인 
print(f"[Color Image]")
print(f"SHAPE: {img_gray.shape} --- DIM : {img_gray.ndim}차원")
print(f"DTYPE: {img_gray.dtype} --- SIZE : {img_gray.size}바이트")

[Color Image]
SHAPE: (511, 568) --- DIM : 2차원
DTYPE: uint8 --- SIZE : 290248바이트


In [17]:
# 이미지 창 띄우기
cv2.imshow("[COLOR]", img_rgb)

# 이미지 창 제어
cv2.waitKey() # ms단위로 입력 0이 default(무한대기)

# 이미지 창 닫기
cv2.destroyAllWindows()

In [20]:
if img_rgb is not None:
    cv2.imshow("[COLOR]", img_rgb)
    while True:
        key=cv2.waitKey() # 키 입력 대기 
        print(f"key => {key} - {hex(key)}") # 입력 키 출력
        
        if key == 27: # ESC키 일때 화면 종료
            cv2.destroyAllWindows()
            break
else:
    print("No image file!!")

key => 27 - 0x1b


## 이미지 저장

In [21]:
img_gray = cv2.imread(file, cv2.IMREAD_GRAYSCALE) # 흑백이미지
save_filename='../data/img/gray_cat.jpg'
gray_file = cv2.imwrite(save_filename, img_gray) # 이미지 저장 

## 이미지 데이터 채널 분리

In [25]:
# 시차줘서 닫기(그냥)
import time
b, g, r = cv2.split(img_rgb)

cv2.imshow("[blue]", b)

cv2.imshow("[green]", g)

cv2.imshow("[red]", r)
cv2.waitKey()

t = 1.5
time.sleep(t)
cv2.destroyWindow("[blue]")
time.sleep(t)
cv2.destroyWindow("[green]")
time.sleep(t)
cv2.destroyWindow("[red]")

## 이미지 채널 병합

In [28]:
# 채널 순서 변경
img_rgb = cv2.merge((r, g, b))

cv2.imshow("RGB IMAGE", img_rgb)

cv2.waitKey()
cv2.destroyAllWindows()

## 이미지 색 공간 변환

In [31]:
src_hsv = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2HSV)

cv2.imshow("src_hsv IMAGE", src_hsv)

# cv2.waitKey()
if cv2.waitKey() or cv2.getWindowProperty("src_hsv", cv2.WND_PROP_VISIBLE) < 1:
    cv2.destroyAllWindows()

## 이미지 크기 변경

In [33]:
down_img = cv2.resize(img_rgb, dsize=None, fx=2, fy=2, interpolation=cv2.INTER_AREA)

cv2.imshow("down_img IMAGE", down_img)
if cv2.waitKey() or cv2.getWindowProperty("src_hsv", cv2.WND_PROP_VISIBLE) < 1:
    cv2.destroyAllWindows()

## 도화지에 그림그리기

In [85]:
img = np.full((800, 800, 3), 255, dtype=np.uint8)
cv2.imwrite("../data/img/white_paper.jpg", img)

True

In [86]:
img = cv2.imread("../data/img/white_paper.jpg", cv2.IMREAD_COLOR)

cv2.imshow('lines', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [87]:
# 이미지 데이터에 그림 그리기 

cv2.line(img, (10, 10), (70, 70), (255, 0, 0))# strat, end, color

cv2.line(img, (50, 50), (150, 50), (255,0,0))   # 파란색 1픽셀 선
cv2.line(img, (200, 50), (300, 50), (0,255,0))  # 초록색 1픽셀 선
cv2.line(img, (350, 50), (450, 50), (0,0,255))  # 빨간색 1픽셀 선

# 하늘색(파랑+초록) 10픽셀 선      
cv2.line(img, (100, 100), (400, 100), (255,255,0), 10)          
# 분홍(파랑+빨강) 10픽셀 선      
cv2.line(img, (100, 150), (400, 150), (255,0,255), 10)          
# 노랑(초록+빨강) 10픽셀 선      
cv2.line(img, (100, 200), (400, 200), (0,255,255), 10)          
# 회색(파랑+초록+빨강) 10픽셀 선  
cv2.line(img, (100, 250), (400, 250), (200,200,200), 10)        
# 검정 10픽셀 선    
cv2.line(img, (100, 300), (400, 300), (0,0,0), 10)                    

# 4연결 선
cv2.line(img, (100, 350), (400, 400), (0,0,255), 20, cv2.LINE_4)   
# 8연결 선
cv2.line(img, (100, 400), (400, 450), (0,0,255), 20, cv2.LINE_8)    
# 안티에일리어싱 선 
cv2.line(img, (100, 450), (400, 500), (0,0,255), 20, cv2.LINE_AA)   
# 이미지 전체에 대각선 
cv2.line(img, (0,0), (500,500), (0,0,255))                      
cv2.imshow('lines', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [45]:
white = np.full((800, 800),255, dtype=np.uint8)
cv2.imshow("white",white)
cv2.waitKey()
cv2.destroyAllWindows()

## 글씨 그리기 cv2.putText()

In [89]:
img = cv2.imread("../data/img/white_paper.jpg", cv2.IMREAD_COLOR)

# sans-serif small
cv2.putText(img, "Plain", (50, 30), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0,0))            
# sans-serif normal
cv2.putText(img, "Simplex", (50, 70), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0,0))        
# sans-serif bold
cv2.putText(img, "Duplex", (50, 110), cv2.FONT_HERSHEY_DUPLEX, 1, (0, 0,0))         
# sans-serif normall X2  ---①
cv2.putText(img, "Simplex", (200, 110), cv2.FONT_HERSHEY_SIMPLEX, 2, (0,0,250)) 

# serif small
cv2.putText(img, "Complex Small", (50, 180), cv2.FONT_HERSHEY_COMPLEX_SMALL, \
            1, (0, 0,0))   
# serif normal
cv2.putText(img, "Complex", (50, 220), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 0,0))
# serif bold
cv2.putText(img, "Triplex", (50, 260), cv2.FONT_HERSHEY_TRIPLEX, 1, (0, 0,0))               
# serif normal X2  ---②
cv2.putText(img, "Complex", (200, 260), cv2.FONT_HERSHEY_TRIPLEX, 2, (0,0,255))               
# hand-wringing sans-serif
cv2.putText(img, "Script Simplex", (50, 330), cv2.FONT_HERSHEY_SCRIPT_SIMPLEX, \
            1, (0, 0,0)) 
# hand-wringing serif
cv2.putText(img, "Script Complex", (50, 370), cv2.FONT_HERSHEY_SCRIPT_COMPLEX, \
            1, (0, 0,0)) 

# sans-serif + italic ---③
cv2.putText(img, "Plain Italic", (50, 430), \
            cv2.FONT_HERSHEY_PLAIN | cv2.FONT_ITALIC, 1, (0, 0,0)) 
# sarif + italic
cv2.putText(img, "Complex Italic", (50, 470), \
            cv2.FONT_HERSHEY_COMPLEX | cv2.FONT_ITALIC, 1, (0, 0,0)) 

cv2.imshow('draw text', img)
cv2.waitKey()
cv2.destroyAllWindows()

## 얼굴 인식

In [101]:
# 이미지 파일 및 정면 얼굴 인식 모델 경로
frontalface_model = "../data/haarcascades/haarcascade_frontalface_default.xml"
img_file = "../data/img/girls.jpg"





# 정면 얼굴 인식 모델 로딩
face_detector = cv2.CascadeClassifier(frontalface_model)

# 이미지 데이터 로딩
imgNP = cv2.imread(img_file)

# imgNP = cv2.resize(imgNP, dsize=None, fx=0.2, fy=0.2, interpolation=cv2.INTER_AREA)



# 이미지에서 정면 얼굴 인식 ==> [return] 인식된 얼굴 수 만큼 위치정보 (x, y, w, h) 반환
face_detections = face_detector.detectMultiScale(imgNP)
print(f"**face_datections RESULT\n{face_detections}")

# 인식된 정면 얼굴 ROI 표시
for (x, y, w, h) in face_detections:
    cv2.rectangle(imgNP, (x, y), (x + w, y + h), (0, 255, 0), 2)

# 화면 출력
cv2.imshow('img', imgNP)
cv2.waitKey()
cv2.destroyAllWindows()

**face_datections RESULT
[[355 135  60  60]
 [159 196  68  68]
 [478 172  95  95]]


In [ ]:
# 1. 영상용
# 
# frontalface_model = '../data/haarcascades/haarcascade_frontalface_alt.xml'
# video_file = '../data/video/1234.mp4'
# 
# face_detector = cv2.CascadeClassifier(frontalface_model)
# camera = cv2.VideoCapture(video_file)
# 
# if not camera.isOpened():
#     print("비디오 파일을 열 수 없습니다.")
#     exit()
# 
# while True:
#     # 비디오 프레임 읽기
#     ret, frame = camera.read()
# 
#     if not ret:
#         print("비디오 프레임을 읽을 수 없습니다.")
#         break
# 
#     # 얼굴 검출
#     face_detections = face_detector.detectMultiScale(frame)
# 
#     # 검출된 얼굴에 사각형 그리기
#     for (x, y, w, h) in face_detections:
#         cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
# 
#     # 프레임 화면에 표시
#     cv2.imshow('Face Detection', frame) 
# 
#     # 'q' 키를 누르면 종료
#     if cv2.waitKey(1) & 0xFF == ord('q'):
#         break
# 
# # 리소스 해제
# camera.release()
# cv2.destroyAllWindows()
# 
# 
# 2. cctv 웹캠용
# 
# import cv2
# import time
# import sys
# import numpy as np
# 
# frontalface_model = '../data/haarcascades/haarcascade_frontalface_alt.xml'
# video_file = '../data/video/1234.mp4'
# 
# face_detector = cv2.CascadeClassifier(frontalface_model)
# camera = cv2.VideoCapture(0)
# 
# if not camera.isOpened():
#     print("비디오 파일을 열 수 없습니다.")
#     exit()
# 
# while True:
#     # 비디오 프레임 읽기
#     ret, frame = camera.read()
# 
#     if not ret:
#         print("비디오 프레임을 읽을 수 없습니다.")
#         break
# 
#     # 얼굴 검출
#     face_detections = face_detector.detectMultiScale(frame)
#     
#     # 검출된 얼굴에 사각형 그리기
#     for (x, y, w, h) in face_detections:
#         cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
# 
#     # 프레임 화면에 표시
#     cv2.imshow('Face Detection', frame) 
# 
#     # 'q' 키를 누르면 종료
#     if cv2.waitKey(1) & 0xFF == ord('q'):
#         break
# 
# # 리소스 해제
# camera.release()
# cv2.destroyAllWindows()