In [1]:
import numpy as np

In [2]:
## ndarray 타입 데이터 생성

In [4]:
## 0으로 채워진 ndarray 객체 생성 => zeros()
np.zeros(2) # C-style => 행 단위

array([0., 0.])

In [5]:
np.zeros((2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [10]:
# 1로 채워진 ndarray 객체 생성 => ones()
np.ones(10), np.ones(10, dtype=np.int32), np.ones((2,5), dtype=bool) # 아무것도 지정안하면 float64, bool은 np.bool_ 로 써도 됨

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]))

In [11]:
 # 랜덤 데이터로 ndarray객체 생성 => random
np.random.randint(1, 5, (3, 5)) # [row, high), size, type

array([[4, 4, 1, 4, 3],
       [3, 1, 2, 3, 2],
       [2, 1, 2, 1, 1]])

In [15]:
# 0 <= 범위 < 1
np.random.rand(2, 2)

array([[0.42447909, 0.83814168],
       [0.65722522, 0.15305469]])

In [17]:
# 정규 분포를 따르는 즁
np.random.rand(2, 2), np.random.rand(1, 2, 3)

(array([[0.3571753 , 0.57777017],
        [0.13038452, 0.65177627]]),
 array([[[0.61174926, 0.59122215, 0.14325104],
         [0.2209125 , 0.53022704, 0.8540824 ]]]))

In [19]:
# 랜덤 고정
np.random.seed(4)

np.random.randn(5)

array([ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152])

In [22]:
data = np.random.randn(10)
print(data)

np.random.shuffle(data) # 원본이 섞임
print(data)

[ 0.39429521  1.98495133  0.02693565  0.35880669 -1.61454139  0.82448138
  0.26043704  1.37718202 -1.37307059 -0.00993354]
[ 0.02693565  1.98495133  0.82448138 -0.00993354 -1.37307059  0.35880669
 -1.61454139  0.26043704  0.39429521  1.37718202]


In [25]:
data.sum(), data.max(), data.min(), data.mean()

(2.2295438040208917,
 1.9849513285299654,
 -1.6145413873732943,
 0.22295438040208918)

In [28]:
data.argmax(), data.argmin()

(1, 6)

In [32]:
np.linspace(1, 9, num=10, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. , 5.8, 6.6, 7.4, 8.2])

In [34]:
a = np.logspace(1, 9, num=10, endpoint=False)
a

array([1.00000000e+01, 6.30957344e+01, 3.98107171e+02, 2.51188643e+03,
       1.58489319e+04, 1.00000000e+05, 6.30957344e+05, 3.98107171e+06,
       2.51188643e+07, 1.58489319e+08])

In [38]:
b = a.ravel()
b[0] = 200

In [39]:
a

array([2.00000000e+02, 6.30957344e+01, 3.98107171e+02, 2.51188643e+03,
       1.58489319e+04, 1.00000000e+05, 6.30957344e+05, 3.98107171e+06,
       2.51188643e+07, 1.58489319e+08])