In [41]:
# 모듈 로딩
from PIL import Image
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

In [1]:
# https://pytorch.org/vision/stable/generated/torchvision.transforms.v2.ToTensor.html#torchvision.transforms.v2.ToTensor

In [4]:
# 이미지 데이터 로딩 
file = "../data/img/img2.png"

In [6]:
catImg = Image.open(file)

catImg.format, catImg.height, catImg.width, catImg.mode, type(catImg)

('PNG', 816, 550, 'RGBA', PIL.PngImagePlugin.PngImageFile)

In [11]:
# 사용법
# 1. 인스턴스 생성
to_tensor = (transforms.ToTensor()) # 채널 위치도 바꿔주고 알잘딱 0~1로 다 해줌 

# 2. 인스턴스 변수 사용
catTS = to_tensor(catImg)

# 3. 변환된 이미지 텐서 확인
print(catTS.shape, catTS.ndim)
print(catTS[0])

torch.Size([4, 816, 550]) 3
tensor([[0.1529, 0.1490, 0.1529,  ..., 0.5725, 0.5569, 0.5686],
        [0.1529, 0.1490, 0.1412,  ..., 0.5686, 0.5490, 0.5451],
        [0.1569, 0.1529, 0.1490,  ..., 0.5569, 0.5490, 0.5373],
        ...,
        [0.6588, 0.6588, 0.6431,  ..., 0.7961, 0.7725, 0.7765],
        [0.6588, 0.6431, 0.6510,  ..., 0.8039, 0.8000, 0.8039],
        [0.6549, 0.6667, 0.6549,  ..., 0.8196, 0.8157, 0.8078]])


# openCV

In [19]:
import cv2

img = cv2.imread(file)
img2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

print("BGR => ", type(img), img.shape, img.ndim)
print("RGB => ", type(img2), img2.shape, img2.ndim) # => shape은 바뀌지 않아요

BGR =>  <class 'numpy.ndarray'> (816, 550, 3) 3
RGB =>  <class 'numpy.ndarray'> (816, 550, 3) 3


In [18]:
# 텐서로 바꾸기 
cat2 = to_tensor(img)
print(cat2.shape, cat2.ndim)
print(cat2[0])

cat3 = to_tensor(img2)
print(cat3.shape, cat3.ndim)
print(cat3[0])

# pillow랑 결과가 좀 다름 계속 바꾸고 바꾸고......

torch.Size([3, 816, 550]) 3
tensor([[0.4000, 0.3961, 0.4000,  ..., 0.8588, 0.8431, 0.8549],
        [0.4000, 0.3961, 0.3882,  ..., 0.8627, 0.8431, 0.8392],
        [0.4039, 0.4000, 0.3961,  ..., 0.8627, 0.8549, 0.8431],
        ...,
        [0.6000, 0.6000, 0.5843,  ..., 0.7373, 0.7137, 0.7176],
        [0.6000, 0.5843, 0.5922,  ..., 0.7373, 0.7412, 0.7451],
        [0.5961, 0.6078, 0.5961,  ..., 0.7529, 0.7569, 0.7490]])
torch.Size([3, 816, 550]) 3
tensor([[0.1529, 0.1490, 0.1529,  ..., 0.5725, 0.5569, 0.5686],
        [0.1529, 0.1490, 0.1412,  ..., 0.5686, 0.5490, 0.5451],
        [0.1569, 0.1529, 0.1490,  ..., 0.5569, 0.5490, 0.5373],
        ...,
        [0.6588, 0.6588, 0.6431,  ..., 0.7961, 0.7725, 0.7765],
        [0.6588, 0.6431, 0.6510,  ..., 0.8039, 0.8000, 0.8039],
        [0.6549, 0.6667, 0.6549,  ..., 0.8196, 0.8157, 0.8078]])


In [45]:
# resizing
preprocessing = transforms.Compose([
    transforms.Resize(size=(50, 50)),
    transforms.RandomHorizontalFlip(0.5),
    transforms.ToTensor(), # 정규화는 무조건 끝쪽에 해야함 
    
])

preprocessed_img = preprocessing(catImg)

# 이미지 데이터 셋
- torchvision.ImageFolder 클래스 사용
    - 이미지 데이터 라벨링
    - 이미지 데이터 전처리
    - 한방에 수행

In [46]:
from torchvision.datasets import ImageFolder 

In [47]:
img_root = "../data/img"

imgDS = ImageFolder(root=img_root, transform=preprocessing)

In [48]:
# 폴더명이 분류 클래스가 됨 
imgDS.classes, imgDS.class_to_idx, imgDS.imgs
# classes -> 라벨 보여줌
# class_to_idx -> 라벨을 숫자로
# imgs -> 파일정보 + 라벨 (경로 뽑아서 볼 수도 있겠지예...)

# => Loader에 넣자!!!

(['cat', 'flower'],
 {'cat': 0, 'flower': 1},
 [('../data/img\\cat\\img3.png', 0), ('../data/img\\flower\\Mine.png', 1)])

In [49]:
imgDL = DataLoader(imgDS)

for (img, label) in imgDL:
    print(img.shape, label.shape)
    break 

# batch_size 아무것도 안주면 1로 들어감 

torch.Size([1, 3, 50, 50]) torch.Size([1])
