# 인공 신경망 모델 클래스 만들기
- 부모 클래스 : nn.Module 상속 받음 
- 필수 오버라이딩 메서드 : _ _init_ _(), forward()

## 1 모듈 로딩

In [1]:
import torch
import torch.nn as nn

In [21]:
# 로지스틱 회귀 모델 클래스 생성 
# Linear + sigmoid
class LogicLinear(nn.Module):
    # 모델 구조 설정
    def __init__(self, in_, out_): # 층(Layer) 생성
        super().__init__() # 부모
        self.layer1 = nn.Linear(in_, 10) # in개 받아서 10개를 내 놓음
        self.sigmoid1 = nn.Sigmoid()
        self.layer2 = nn.Linear(10, out_) 
        self.sigmoid2 = nn.Sigmoid()
        
    # 순방향 학습진행 콜백 함수
    def forward(self, x): # 순전파 학습 
        y = self.layer1(x)
        z = self.sigmoid(y)
        y = self.layer2(z)
        z = self.sigmoid2(y)
        return z

In [22]:
# 모델 인스턴스 생성 
l1 = LogicLinear(10, 3)
print(f"====== 모델 구조 확인 ======\n {l1}")

====== 모델 구조 확인 ======
 LogicLinear(
  (layer1): Linear(in_features=10, out_features=10, bias=True)
  (sigmoid1): Sigmoid()
  (layer2): Linear(in_features=10, out_features=3, bias=True)
  (sigmoid2): Sigmoid()
)


In [19]:
print(f"모델구성 w, b ======")
for param in l1.parameters(): print(param)
    

모델구성 w, b ======
Parameter containing:
tensor([[ 0.2920, -0.2056, -0.3652, -0.4567],
        [ 0.3676,  0.2554,  0.0674, -0.2936],
        [-0.4273, -0.3791, -0.4951,  0.3379],
        [-0.1535, -0.3372,  0.3916, -0.3613],
        [ 0.4267, -0.4245,  0.2558,  0.4539],
        [-0.3521, -0.1357, -0.2247,  0.2397],
        [-0.0635,  0.2827, -0.0514,  0.3147],
        [ 0.4492,  0.0621,  0.3826, -0.1314],
        [-0.0459,  0.2734,  0.2838, -0.4054],
        [ 0.2853,  0.3221, -0.0448, -0.1897]], requires_grad=True)
Parameter containing:
tensor([ 0.2469, -0.0732,  0.0263, -0.3689, -0.0566,  0.0078, -0.4997,  0.1733,
        -0.2767,  0.2207], requires_grad=True)
Parameter containing:
tensor([[ 0.2895, -0.1073, -0.1318, -0.1073,  0.0857,  0.0545,  0.0398,  0.2893,
         -0.2863,  0.2360]], requires_grad=True)
Parameter containing:
tensor([-0.2280], requires_grad=True)
