In [7]:
# Pandas를 pd라는 이름으로 임포트한다
import pandas as pd
import numpy as np

In [4]:
# 학생번호를 인덱스로 csv 파일을 읽어들여, 변수 df에 저장
df = pd.read_csv('../data/ch1_sport_test.csv',
                 index_col='학생번호')
# 변수 df를 표시
df

학년    악력  윗몸일으키기  점수  순위
학생번호                          
1      1  40.2      34  15   4
2      1  34.2      14   7  10
3      1  28.8      27  11   7
4      2  39.0      27  14   5
5      2  50.9      32  17   2
6      2  36.5      20   9   9
7      3  36.6      31  13   6
8      3  49.2      37  18   1
9      3  26.0      28  10   8
10     3  47.4      32  16   3

In [5]:
df["악력"]

학생번호
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4
Name: 악력, dtype: float64

## Section 1.1 데이터의 크기

In [6]:
df.shape

(10, 5)

# CH02 1차원 데이터 정리

In [9]:
# Jupyter Notebook의 출력을 소수점 이하 3자리로 제한
%precision 3
# DF의 출력을 소수점 이하 3자리로 제한
pd.set_option("display.precision", 3)

In [10]:
0.3

0.300

In [13]:
df = pd.read_csv('../data/ch2_scores_em.csv',
                 index_col='student number')
# 변수 df를 표시
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [15]:
scores = np.array(df["english"])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [16]:
scores_df = pd.DataFrame({'score':scores},
                         index=pd.Index(['A', 'B', 'C', 'D', 'E',
                                         'F', 'G', 'H', 'I', 'J'],
                                        name='student'))
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

## 2.1 데이터 중심의 지표

In [18]:
np.mean(scores)

55.000

In [19]:
scores_df.mean()

score    55.0
dtype: float64

In [20]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [21]:
np.median(scores)

56.500

In [22]:
scores_df.median()

score    56.5
dtype: float64

### 2.1.3 최빈값

In [24]:
pd.Series([1, 1, 1, 2, 2, 3]).mode()

0    1
dtype: int64

## 2.2 데이터의 산포도 지표

### 2.2.1 분산과 표준편차

In [27]:
# 편차
mean = np.mean(scores)
deviation = scores-mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [28]:
another_scores = [50, 60, 58, 54, 51, 56, 57, 53, 52, 59]
another_mean = np.mean(another_scores)
another_deviation = another_scores - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [29]:
np.mean(deviation) # 편차의 평균은 0!! = 합이 0이라는 의미 

0.000

In [31]:
summary_df = scores_df.copy()
summary_df["diviation"] = deviation
summary_df

score  diviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

In [32]:
summary_df.mean()

score        55.0
diviation     0.0
dtype: float64

In [33]:
np.var(scores) # numpy의 var 함수

86.000

In [34]:
scores_df.var() # pandas이 var 메서드

score    95.556
dtype: float64

In [36]:
scores_df.var(ddof=0) # pandas이 var 메서드

score    86.0
dtype: float64

둘의 결과가 다름!! -> numpy는 표본분산이 기본, pandas(ddof=1)는 불편분산이 기본 pandas로 ddof=0하면 같은 결과 

In [35]:
summary_df['square of deviation'] = np.square(deviation)
summary_df

score  diviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
J           58        3.0                  9.0

### 2.2.2 범위와 사분위 범위

- range  
range는 데이터 전체를 보는 것이 아닌 __최솟값__ 과 __최댓값__ 만으로 산포도를 표현하는 방법 -> 이상값에 약함

In [38]:
np.max(scores) - np.min(scores)

28

- 사분위 범위  
  데이터의 __상위수%__ ,__하위수%__ 에 위치하는 값의 차이를 취하는 것  
  IQR(사분위 범위) = Q3 - Q1 

In [39]:
scores_Q1 = np.percentile(scores, 25)
scores_Q3 = np.percentile(scores, 75)
scores_IQR = scores_Q3 - scores_Q1
scores_IQR

15.000

### 2.2.3 데이터의 지표 정리

In [40]:
# describe를 사용하면 다 구해짐
pd.Series(scores).describe()

count    10.000
mean     55.000
std       9.775
min      41.000
25%      48.250
50%      56.500
75%      63.250
max      69.000
dtype: float64

## 2.3 데이터의 정규화  
: 데이터를 통일된 지표로 변환하는 것

### 2.3.1 표준화  
:데이터에서 평균을 빼고 표준편차로 나누는 작업 -> 표준화 변량 / Z 점수라고 함

In [44]:
z = (scores - np.mean(scores)) / np.std(scores)
z

array([-1.402,  1.51 ,  0.108, -1.51 ,  0.216, -0.755,  1.078, -0.647,
        1.078,  0.323])

In [45]:
np.mean(z), np.std(z, ddof=0)

(-0.000, 1.000)

### 2.3.2 편찻값  
평균이 50, 표준편차가 10이 되도록 정규화한 값

# 2.4 1차원 데이터의 시각화

In [48]:
english_scores = np.array(df["english"])

In [49]:
df["english"].describe()

count    50.00
mean     58.38
std       9.80
min      37.00
25%      54.00
50%      57.50
75%      65.00
max      79.00
Name: english, dtype: float64

### 2.4.1 도수분포표  
: 데이터의 분포 상태를 세부적으로 알고 싶을 때  
-> 데이터 값들을 몇 개의 구간으로 나누고, 해당 구간에 몇 개의 데이터가 들어가는지 세는 법  

In [53]:
freq, a = np.histogram(english_scores, bins=10, range=(0, 100))
freq, _ = np.histogram(english_scores, bins=10, range=(0, 100))
freq

array([ 0,  0,  0,  2,  8, 16, 18,  6,  0,  0], dtype=int64)

In [54]:
freq_class = [f"{i}~{i+10}" for i in range(0, 100, 10)]

freq_dist_df = pd.DataFrame({"frequency":freq}, index=pd.Index(freq_class, name="class"))

In [55]:
freq_dist_df

frequency
class            
0~10            0
10~20           0
20~30           0
30~40           2
40~50           8
50~60          16
60~70          18
70~80           6
80~90           0
90~100          0