# 텐서(Tensor) 살펴보기
- Pytorch에서 데이터 저장 자료형
- 모델 입력(input), 출력(output) 데이터 형태

- 모듈로딩

In [2]:
import torch

- Tensor 속성 관련함수

In [4]:
# 매개변수 : 텐서 인스턴스
def print_attribute(tensor, name):
    print(f"[Tensor {name}]\'s Attribute")
    print(f" - tensor.shape: {tensor.shape}")
    print(f" - tensor.ndim: {tensor.ndim}")
    print(f" - tensor.dtype: {tensor.dtype}")
    print(f" - tensor.device: {tensor.device}")
    print(f" - tensor.requires_grad: {tensor.requires_grad}")
    print(f" - tensor.data: {tensor.data}")

- Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    * 타입별 텐서 클래스 생성자 활용
    * ex) IntTensor(), FloatTensor(), BoolTensor()

In [18]:
# 정수 타입 텐서
t1 = torch.IntTensor(10) # scalar
t2 = torch.IntTensor([10, 20])
t3 = torch.BoolTensor([1, 0, 3])
t4 = torch.FloatTensor([10, 20])

In [15]:
print_attribute(t1, "t1")

[Tensor t1]'s Attribute
 - tensor.shape: torch.Size([10])
 - tensor.ndim: 1
 - tensor.dtype: torch.int32
 - tensor.device: cpu
 - tensor.requires_grad: False
 - tensor.data: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)


In [16]:
print_attribute(t2, "t2")

[Tensor t2]'s Attribute
 - tensor.shape: torch.Size([2])
 - tensor.ndim: 1
 - tensor.dtype: torch.int32
 - tensor.device: cpu
 - tensor.requires_grad: False
 - tensor.data: tensor([10, 20], dtype=torch.int32)


In [17]:
print_attribute(t3, "t3")

[Tensor t3]'s Attribute
 - tensor.shape: torch.Size([3])
 - tensor.ndim: 1
 - tensor.dtype: torch.bool
 - tensor.device: cpu
 - tensor.requires_grad: False
 - tensor.data: tensor([ True, False,  True])


In [19]:
print_attribute(t4, "t4")

[Tensor t4]'s Attribute
 - tensor.shape: torch.Size([2])
 - tensor.ndim: 1
 - tensor.dtype: torch.float32
 - tensor.device: cpu
 - tensor.requires_grad: False
 - tensor.data: tensor([10., 20.])


- Tensor 생성(2) 원하는 값으로 텐서 생성, 데이터를 보고 type이 정해짐 => torch.tensor()

In [20]:
t1=torch.tensor(10) # scalar 데이터, int64
print_attribute(t1, "t1") # scalar 데이터, int64

[Tensor t1]'s Attribute
 - tensor.shape: torch.Size([])
 - tensor.ndim: 0
 - tensor.dtype: torch.int64
 - tensor.device: cpu
 - tensor.requires_grad: False
 - tensor.data: 10


In [21]:
t1=torch.tensor(10.) 
print_attribute(t1, "t1")

[Tensor t1]'s Attribute
 - tensor.shape: torch.Size([])
 - tensor.ndim: 0
 - tensor.dtype: torch.float32
 - tensor.device: cpu
 - tensor.requires_grad: False
 - tensor.data: 10.0


In [23]:
t1=torch.tensor(10, dtype=torch.int32) 
print_attribute(t1, "t1")

[Tensor t1]'s Attribute
 - tensor.shape: torch.Size([])
 - tensor.ndim: 0
 - tensor.dtype: torch.int32
 - tensor.device: cpu
 - tensor.requires_grad: False
 - tensor.data: 10


In [24]:
t1=torch.tensor([[10, 3, 45]], dtype=torch.int8) 
print_attribute(t1, "t1")

[Tensor t1]'s Attribute
 - tensor.shape: torch.Size([1, 3])
 - tensor.ndim: 2
 - tensor.dtype: torch.int8
 - tensor.device: cpu
 - tensor.requires_grad: False
 - tensor.data: tensor([[10,  3, 45]], dtype=torch.int8)


In [ ]:
######

In [31]:
torch.zeros(2,dtype=torch.int8)

tensor([0, 0], dtype=torch.int8)

In [30]:
torch.ones(2,5,dtype=torch.int8)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)

tensor([[1., 0., 0.]])

In [32]:
# 이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zeros_like(), ones_like()
img = torch.tensor([[1,2,3,4,5],[7,8,9,5,2]])
print(torch.zeros_like(img))

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [33]:
print(torch.ones_like(img))

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


In [36]:
print(torch.full_like(img, 7)) 

tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])


In [ ]:
# 대각선 방향으로 1채우기 
torch.full ( (2,),4 )

torch.eye(1,3)

In [37]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [40]:
torch.eye(5,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [41]:
# 임의의 값으로 채운 Tensor
torch.manual_seed(12) # 랜덤 초기값 설정

In [43]:
torch.rand(2, 3)

tensor([[0.6373, 0.2421, 0.7312],
        [0.7224, 0.1992, 0.6948]])

In [50]:
torch.randint(low=0, high=2, size=(2,3))

tensor([[1, 1, 1],
        [0, 0, 0]])

- Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), torch()

In [63]:
# 데이터 생성

import numpy as np

data= np.array([11,22,33])
print(data, type(data))

[11 22 33] <class 'numpy.ndarray'>


In [72]:
t1 = torch.from_numpy(data)
t1

tensor([11, 22, 33], dtype=torch.int32)

In [70]:
t2 = torch.as_tensor(data)
t2

tensor([11, 22, 33], dtype=torch.int32)

In [71]:
t3 = torch.tensor(data)
t3

tensor([11, 22, 33], dtype=torch.int32)

In [73]:
data[0] = 100
print(t1, t2, t3) # copy()인지 주소 공유인지 유의할 것 

tensor([100,  22,  33], dtype=torch.int32) tensor([100,  22,  33], dtype=torch.int32) tensor([11, 22, 33], dtype=torch.int32)
