In [1]:
## Tensor 원소/요소 접근

In [2]:
# 모듈 로딩
import torch

In [6]:
# 텐서 생성
points = torch.tensor([[4., 2.], [5, 3], [6, 4]], dtype=torch.int16)

C:\Users\kdp\AppData\Local\Temp\ipykernel_15112\3762021253.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  points = torch.tensor([[4., 2.], [5, 3], [6, 4]], dtype=torch.int16)


In [7]:
# tensor 원소 1개 접근
# 데이터 3 추출 
print(points[1, 1])

tensor(3, dtype=torch.int16)


In [9]:
# 1번 행부터 모든 행 추출
print(points[1:])

tensor([[5, 3],
        [6, 4]], dtype=torch.int16)


In [10]:
# 마지막 4가지고 오기
print(points[-1, -1])

tensor(4, dtype=torch.int16)


In [17]:
torch.FloatTensor([[1, 2]]).shape

torch.Size([1, 2])

In [31]:
torch.FloatTensor([[1, 2]]).size()

torch.Size([1, 2])

In [19]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])

print(f"m1.shape => {m1.shape}, m2.shape => {m2.shape}")

m1.shape => torch.Size([1, 2]), m2.shape => torch.Size([1])


In [21]:
m3 = m1 + m2
print(f"m3.shape => {m3.shape}, {m3}")

m3.shape => torch.Size([1, 2]), tensor([[4., 5.]])


In [22]:
torch.FloatTensor([[3], [4]]).shape

torch.Size([2, 1])

In [33]:
a = torch.FloatTensor([3, 4])
print(f"a.shape => {a.size()}")
print(f"a.ndim => {a.ndim}")


a.shape => torch.Size([2])
a.ndim => 1


In [30]:
m2.mul(m1)

tensor([[3., 6.]])

In [39]:
torch.FloatTensor([[1], [5]]) * torch.FloatTensor([3, 4])

tensor([[ 3.,  4.],
        [15., 20.]])

In [37]:
torch.FloatTensor([[1], [5]]).matmul(torch.FloatTensor([3, 4]))

RuntimeError: size mismatch, got input (2), mat (2x1), vec (2)

In [38]:
torch.FloatTensor([[1], [5]]).matmul(torch.FloatTensor([[3, 4]]))

tensor([[ 3.,  4.],
        [15., 20.]])

In [43]:
a = torch.FloatTensor([[1, 5]])
a.shape

torch.Size([1, 2])

In [45]:
b = torch.FloatTensor([[1], [5]])
b.shape

torch.Size([2, 1])

In [46]:
a * b

tensor([[ 1.,  5.],
        [ 5., 25.]])

In [47]:
a.matmul(b)

tensor([[26.]])