# Tensor shape 변경
- reshape() 
- view()

-> 원소 개수가 유지됨, 기존 텐서 공유(원본 바꾸면 이것도 바뀐다!!)

In [1]:
# 모듈 로딩
import torch

In [103]:
# 텐서 데이터 생성
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t1.shape, t1.ndim)

torch.Size([2, 3]) 2


In [104]:
# 2행 3열을 3행 2열 형태로 변경 : 원소 개수는 동일하게 6개 
t1.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [105]:
t1.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [110]:
t1.view(-1) # -1은 알아서 지정

torch.Size([6])

In [111]:
t1.view(-1,1)

torch.Size([6, 1])

In [147]:
def print_info(m, name):
    print(f"====={name} 정보=====\nshpae => {m.shape}\n데이터 연속? {m.is_contiguous()}\n주소지 => {m.data_ptr()}\n데이터 => \n{m.storage()}\n데이터 stride => {m.stride()}") 
    print()
    # is_contiquous 메모리가 연속되어 있나요? 라는 뜻
    # row 읽고 다음 row읽고 다음 row

- 전치 : 행 <-> 열 변경

In [149]:
print_info(t1, "t")

t2 = t1.T
print_info(t2, "t2")

t3 = t1.reshape(3, 2)
print_info(t3, "t3")

t1, t2, t3

=====t 정보=====
shpae => torch.Size([2, 3])
데이터 연속? True
주소지 => 4076687334720
데이터 => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
데이터 stride => (3, 1)

=====t2 정보=====
shpae => torch.Size([3, 2])
데이터 연속? False
주소지 => 4076687334720
데이터 => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
데이터 stride => (1, 3)

=====t3 정보=====
shpae => torch.Size([3, 2])
데이터 연속? True
주소지 => 4076687334720
데이터 => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
데이터 stride => (2, 1)


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [144]:
print_info(t1, "t")

t2 = t1.view(3, 2)
print_info(t2, "t2")

t3 = t1.reshape(3, 2)
print_info(t3, "t3")

t1, t2 ,t3

=====t 정보=====
shpae => torch.Size([2, 3])
데이터 연속? True
주소지 => 4076687334720
데이터 =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
데이터 stride => (3, 1)
=====t2 정보=====
shpae => torch.Size([3, 2])
데이터 연속? True
주소지 => 4076687334720
데이터 =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
데이터 stride => (2, 1)
=====t3 정보=====
shpae => torch.Size([3, 2])
데이터 연속? True
주소지 => 4076687334720
데이터 =>  1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
데이터 stride => (2, 1)


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [ ]:

print_info(t1, "t")

t2 = t1.view(3, 2)
print_info(t2, "t2")

t3 = t1.reshape(3, 2)
print_info(t3, "t3")

In [158]:
t2 = t1.T # 문제 생성!!
print_info(t2, "t2")
t2

=====t2 정보=====
shpae => torch.Size([3, 2])
데이터 연속? False
주소지 => 4076687334720
데이터 => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
데이터 stride => (1, 3)


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [159]:
t3 = t2.reshape(-1, 6) # 안맞으면 새로 팜
print_info(t3, "t3")
t3

=====t3 정보=====
shpae => torch.Size([1, 6])
데이터 연속? True
주소지 => 4076687334208
데이터 => 
 1
 4
 2
 5
 3
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
데이터 stride => (6, 1)


tensor([[1, 4, 2, 5, 3, 6]])

In [152]:
t2.view(-1, 6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [45]:
t1.view(-1, 6)

tensor([[1, 2, 3, 4, 5, 6]])

# Tensor 데이터의 메모리 저장 즉 메타 데이터 
- 현재 저장 형태, 검색 방향 정보, 시작 정보

In [32]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t1.shape, t1.ndim)
print(f"t1.storage() => \n{t1.storage()}") # 메모리에 어떤 순서로 저장되어 있는지 알 수 있음 
print(f"t1.storage_offset() => {t1.storage_offset()}")
print(f"t1.stride() => {t1.stride()}") # 다음 줄로 갈 때 몇 번가야하는지 
print(f"t1.is_contiguous() => {t1.is_contiguous()}") # 연속되어 있음(t1.storage에서 확인할 수 있음)

torch.Size([2, 3]) 2
t1.storage() => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1.storage_offset() => 0
t1.stride() => (3, 1)
t1.is_contiguous() => True


In [33]:
t2 = t1.view(-1, 2) # 행과 열을 안바꾼 상태
print(t1.shape, t1.ndim)
print(f"t1.storage() => \n{t1.storage()}") # 메모리에 어떤 순서로 저장되어 있는지 알 수 있음 
print(f"t1.storage_offset() => {t1.storage_offset()}")
print(f"t1.stride() => {t1.stride()}") # 다음 줄로 갈 때 몇 번가야하는지 
print(f"t1.is_contiguous() => {t1.is_contiguous()}") # 연속되어 있음(t1.storage에서 확인할 수 있음)

torch.Size([2, 3]) 2
t1.storage() => 
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
t1.storage_offset() => 0
t1.stride() => (3, 1)
t1.is_contiguous() => True


reshape은 copy
T하면 주소지는 공유 / stride가 바뀜 공유가 힘들엉
view는 원본 공유

# 차원 제거 / 추가
- tensor.squeeze() : 텐서에서 차원찍었을 때 1인 것 제거 -> [] 한겹 벗기는 거
- tensor.unsqueeze(dim) : 텐서에 차원 1인 것 추가

In [61]:
# 데이터 생성
t1 = torch.tensor([[1, 2], [4, 5]])
t2 = torch.tensor([[1, 2, 3, 4]])
t3 = torch.tensor([[[1, 2, 3, 4]]])
t4 = torch.tensor([[1], [2], [3], [4]])

In [69]:
print(f"t1.shape => {t1.shape}, t1.dim => {t1.ndim}D, 주소 => {t1.data_ptr()}")
print(f"t2.shape => {t2.shape}, t2.dim => {t2.ndim}D, 주소 => {t2.data_ptr()}")
print(f"t3.shape => {t3.shape}, t2.dim => {t3.ndim}D, 주소 => {t3.data_ptr()}")
print(f"t4.shape => {t4.shape}, t2.dim => {t4.ndim}D, 주소 => {t4.data_ptr()}")

t1.shape => torch.Size([2, 2]), t1.dim => 2D, 주소 => 4076687458880
t2.shape => torch.Size([1, 4]), t2.dim => 2D, 주소 => 4076687459008
t3.shape => torch.Size([1, 1, 4]), t2.dim => 3D, 주소 => 4076687459072
t4.shape => torch.Size([4, 1]), t2.dim => 2D, 주소 => 4076687459200


In [70]:
t11 = t1.squeeze()
t22 = t2.squeeze()
t33 = t3.squeeze(dim=0)  # 1, 1, 4 였을 때 0번이 1이면 
t44 = t4.squeeze()
print(f"t1 차원 축소 => {t11.shape}, t1.dim => {t11.ndim}D, 주소 => {t11.data_ptr()}")
print(f"t2 차원 축소 => {t22.shape}, t2.dim => {t22.ndim}D, 주소 => {t22.data_ptr()}")
print(f"t3 차원 축소 => {t33.shape}, t2.dim => {t33.ndim}D, 주소 => {t33.data_ptr()}")
print(f"t4 차원 축소 => {t44.shape}, t2.dim => {t44.ndim}D, 주소 => {t44.data_ptr()}")

t1 차원 축소 => torch.Size([2, 2]), t1.dim => 2D, 주소 => 4076687458880
t2 차원 축소 => torch.Size([4]), t2.dim => 1D, 주소 => 4076687459008
t3 차원 축소 => torch.Size([1, 4]), t2.dim => 2D, 주소 => 4076687459072
t4 차원 축소 => torch.Size([4]), t2.dim => 1D, 주소 => 4076687459200


In [77]:
# 원소 / 요소 수 변경 없이 차원 1 증가 시키기 => torch.unsqueeze()
print(f"t1 정보 => {t1.shape}, t1.dim => {t1}D, {t1.data_ptr()}")
t1

t1 정보 => torch.Size([2, 2]), t1.dim => tensor([[1, 2],
        [4, 5]])D, 4076687458880


tensor([[1, 2],
        [4, 5]])

In [82]:
t11 = t1.unsqueeze(dim=0)
t22 = t1.unsqueeze(dim=-1)

print(f"t1 차원 추가 => {t11.shape}, {t11.ndim}D => {t11.data_ptr()}")
print(f"t1 차원 추가 => {t22.shape}, {t22.ndim}D => {t22.data_ptr()}")

t1 차원 추가 => torch.Size([1, 2, 2]), 3D => 4076687458880
t1 차원 추가 => torch.Size([2, 2, 1]), 3D => 4076687458880


# Tensor 차원 / 형태 변경

In [92]:
t1 = torch.tensor([[[1, 2], [11, 22], [44, 55]]])

print(f"t1 => {t1.shape}, {t1.ndim}D") # [1, 3, 2] -> 0번, 1번, 2번

t1 => torch.Size([1, 3, 2]), 3D


In [94]:
# 2개의 차원을 변경하는 메서드
t11 = t1.transpose(0, 2) # 2개씩만 가능 
print(f"t11 => {t11.shape}, {t11.ndim}D")

t11 => torch.Size([2, 3, 1]), 3D


In [100]:
t1

tensor([[[ 1,  2],
         [11, 22],
         [44, 55]]])

In [95]:
t11

tensor([[[ 1],
         [11],
         [44]],

        [[ 2],
         [22],
         [55]]])

In [97]:
# 모든 차원을 변경하는 메서드
t22 = t1.permute(1, 2, 0)
print(f"t22 => {t22.shape}, {t22.ndim}")

t22 => torch.Size([3, 2, 1]), 3


In [102]:
print(f"{t1.data_ptr()}, {t22.data_ptr()}, {t11.data_ptr()}") # 데이터 참조 위치는 같음 -> 마찬가지로 meta data가 바뀌는 것 

4076687335168, 4076687335168, 4076687335168


92p none
과제 : [03-12 과제]
(1) Tensor 생성, 형태 변형, 속성 정보
(2) 인공지능 관련 수학
[참고]https://thebook.io/080246/0099/
** 빅분기 시험 4주 남았습니다.
미리 계획 세우시고 준비하셔요~