In [2]:
import torch

1. 화면 상에서 Pytorch 데이터를 저장하는 단위는 __tensor__ 입니다.  
2. n차원 연산 가능
3. int(부호 있음), uint(부호 없음)

In [7]:
# 4.Pytorch에 논리형 데이터로 저장 후 속성을 출력하는 코드를 작성하세요. 

data = torch.tensor([10, -5, 1.4, 7, 0, -1, 0], dtype=bool)
data

tensor([ True,  True,  True,  True, False,  True, False])

In [21]:
# 5. 10개의 0데이터를 2차원으로 저장하는 코드

data5 = torch.zeros(10,1)
print(data5)
print(data5.ndim, "D")

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
2 D


In [14]:
# 6. 5개의 1데이터가 대각선으로 저장되는 2차원 저장 코드
data = torch.eye(5)
data

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
# 7. 5번에서 저장된 형태와 동일하지만 값이 3이 저장된 코드를 작성하세요.
data7 = torch.full_like(data5, 3)
data7

tensor([[3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [77]:
# 8. ndarray데이터를 Pytorch에 저장하는 코드를 작성하세요.(dtype = float32)
import numpy as np
array1 = np.arange(1, 101, 7)
data8 = torch.as_tensor(array1, dtype=torch.float32)
# data8 = torch.from_numpy(array1) # from_numpy는 dtype은 못 받음
data8, data8.dtype

(tensor([ 1.,  8., 15., 22., 29., 36., 43., 50., 57., 64., 71., 78., 85., 92.,
         99.]),
 torch.float32)

In [78]:
# 9. 아래 조건에 맞는 데이터를 Pytorch에 저장하는 코드를 작성하세요. 
img_name = "flower.jpg"
img = torch.randint(1, 255, (80, 120)) # 이미지는 가로, 세로 
img.type(torch.int8)
torch.save(img, img_name)

In [86]:
# 10. 아래 조건에 맞도록 코드를 작성하세요. 
# 10 - 1) 1D로 저장 임의의 정수 10개
data10_1 = torch.tensor(range(1, 11))
data10_1, data10_1.ndim, data10_1.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 1, torch.Size([10]))

In [54]:
# 10 - 2) 저장된 데이터를 요소 수 변경 없이 3D로 변환
data10_2 = torch.unsqueeze(data10_1, dim=0)
data10_2 = torch.unsqueeze(data10_2, dim=0)
data10_2

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])

In [83]:
# 10 - 3) 2에 저장된 데이터의 2개 차원 변경한 3D로 변환
data10_2.transpose(1, 0)

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])

In [87]:
# 10 - 4) 2에 저장된 데이터의 3개 차원 모두 변경한 3D로 변환
data10_2.permute(1, 2, 0)

tensor([[[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]])

In [90]:
# 11. 아래 조건에 맞도록 코드를 작성하세요.
import pandas as pd
# (1) 데이터 저장
data = pd.DataFrame({"국어" : [90, 70, 80], "영어" : [70, 100, 80], "수학" : [99, 88, 77]})

# (2) 과목별 합계 평균 최고점
data.sum(axis = 1)
data.mean(axis = 1)
data.max(axis = 1)

0     99
1    100
2     80
dtype: int64

In [91]:
# (3) 한 사람의 과목 합계 평균 최고점
data.sum(axis = 0)
data.mean(axis = 0)
data.max(axis = 0)

국어     90
영어    100
수학     99
dtype: int64

In [103]:
# 12. 아래 조건에 맞도록 코드를 작성하세요. 
# 1. 데이터 저장
data2 = torch.tensor([[0.5], [0.2], [0.7]])
data1 = torch.tensor(data.values, dtype=data2.dtype)

# 2.사칙연산


In [94]:
# 3.행렬곱셈
data1.matmul(data2)

tensor([[128.3000],
        [116.6000],
        [109.9000]])

In [108]:
test = ["+", "-", "/", "*"]

for t in test:
    print(f"=========== {t} 연산 결과 ===========")
    temp = f"data1{t}data2"
    print(eval(temp))
    print()

=========== + 연산 결과 ===========
tensor([[ 90.5000,  70.5000,  99.5000],
        [ 70.2000, 100.2000,  88.2000],
        [ 80.7000,  80.7000,  77.7000]])

=========== - 연산 결과 ===========
tensor([[89.5000, 69.5000, 98.5000],
        [69.8000, 99.8000, 87.8000],
        [79.3000, 79.3000, 76.3000]])

=========== / 연산 결과 ===========
tensor([[180.0000, 140.0000, 198.0000],
        [350.0000, 500.0000, 440.0000],
        [114.2857, 114.2857, 110.0000]])

=========== * 연산 결과 ===========
tensor([[45.0000, 35.0000, 49.5000],
        [14.0000, 20.0000, 17.6000],
        [56.0000, 56.0000, 53.9000]])
